### ISSUE TITLE
post-calendar: UnhandledPromiseRejectionWarning: TimeoutError: Request timed out

### ISSUE THREAD

**Issue by zhufree** [sxzz/jike-tool#1]
```(node:5868) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created) 
Hello, @zhufree
获取数据中...
(node:5868) UnhandledPromiseRejectionWarning: TimeoutError: Request timed out
    at Timeout._onTimeout (file:///E:/jike-tool/node_modules/.pnpm/ky@0.28.7/node_modules/ky/distribution/utils/time.js:8:16)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:5868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
能拿到profile应该不是token的问题吧，是我网太差了吗

**Comment by zhufree** [comment]
like-raking也是一样，获取427条动态之后就一直错误了
![image](https://user-images.githubusercontent.com/6095752/146764149-1d359106-f876-4255-862a-e9f2c2f278d4.png)

**Comment by sxzz** [comment]
1. 可能是你的动态太多了，开源版本还没做分页，一次性获取太多导致超时，后续优化；
2. 点赞排行榜目前没维护了，可以用浏览器版本 https://github.com/sxzz/jike-plus .

**Comment by zhufree** [comment]
> 1. 可能是你的动态太多了，开源版本还没做分页，一次性获取太多导致超时，后续优化；
> 2. 点赞排行榜目前没维护了，可以用浏览器版本 https://github.com/sxzz/jike-plus .

确实我的动态很多。。。

**Comment by sxzz** [comment]
分页已经做好了
